### ISSUE TITLE
Issue tracker integration on private repos

### ISSUE THREAD

**Issue by vassdeniss** [dail8859/TurtleHub#12]
I would like to use TurtleHub with one of my private repos but I am receiving the following warning when adding locally:
![image](https://user-images.githubusercontent.com/72888249/146647760-c987d469-44e9-4f3a-b788-582f5eca7b32.png)

**Comment by RevZero** [comment]
@vassdeniss Did you figure this out or why did you close this issue?

**Comment by vassdeniss** [comment]
> @vassdeniss Did you figure this out or why did you close this issue?

I am so sorry, I do not recall how I did it or if it was possible, but I think I gave up on it.
