### ISSUE TITLE
How to open issure windows?

### ISSUE THREAD

**Issue by bluelovers** [dail8859/TurtleHub#3]
im use TortoiseGit 2.3.0

i didn't found where can see issure lol
![20170110-062212-1](https://cloud.githubusercontent.com/assets/167966/21786059/2afc5738-d6fd-11e6-9c6a-ae9a336755c6.png)

**Comment by dail8859** [comment]
Hi @bluelovers 

That window is just to set up the parameters for the repository. There will be a now be a new button when you commit. Your commit window will now look like this:

![capture](https://cloud.githubusercontent.com/assets/3694843/21786357/71121bb6-d691-11e6-89d5-662d826413ad.PNG)
